### PR TITLE
Update type definitions

### LINKED ISSUE #113: Type error on typescript
Unable to compile using typescript.

Error :
`node_modules/node-thermal-printer/node-thermal-printer.d.ts:18:14 - error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).`

Probably need to specify return type of Promise<void | any>.

### PR DESCRIPTION
**Pull request by hadeeb**
closes #113

### CODE REVIEW

**Comment by Klemen1337** [comment]
@hadeeb I don't know how I didn't see this pull request. I was working on node-thermal-printer.d.ts today. Now we have merge conflicts :(

**Comment by Klemen1337** [comment]
@hadeeb I don't know how I didn't see this pull request. I was working on node-thermal-printer.d.ts today. Now we have merge conflicts :(

**Comment by Klemen1337** [comment]
I see that I have missed the drive, upsideDown and append, other than that we made very similar changes 😄

**Comment by hadeeb** [comment]
Updated the PR with changes in master and included tsdoc comments

**Comment by Klemen1337** [comment]
@hadeeb Thank you :beer:

**Pull request merged**
