### PR TITLE
Don't bother the user anymore with code pages - accept UTF-8 and print it

### PR DESCRIPTION
**Pull request by kozmoz**
This improvement tries to match the unicode characters in the input string to the correct code page. Characters without a match are printed as question mark (?). 

So eg if the user tries to print a Euro currency sign, it will make the translation from Euro in text to the correct code automatically. No need to find and print the character code for Euro. The user never has the need to deal with any of the character set or code page junk anymore - they just send unicode UTF8 strings and the library deals with it.

It adds a dependency to iconv-lite. 
Also still plan to add some unit tests.

### CODE REVIEW

**Comment by Cattpot** [comment]
that would be a lifesaver 👍

**Comment by KhanMaytok** [comment]
Please merge this :D

**Comment by kozmoz** [comment]
Any chance this code will make it to the base branch? Or at least are you open to such a change to the code? @Klemen1337

**Comment by KhanMaytok** [comment]
I've tested the new changes and the command printer.drawLine(); prints  "AAAAAAAAAAAAAAAAAAAA"

**Comment by Klemen1337** [comment]
I do not want any more dependencies, also @KhanMaytok said drawLine prints wrong?

**Comment by kozmoz** [comment]
Okay, fair enough. Might fork the project in the future.

**Comment by Klemen1337** [comment]
@kozmoz I couldn't merge your commit because the code changed so much, but I implemented your style for encoding. So thank you 🍻

**Pull request closed without merging**
