### PR TITLE
Charsets extended, encoding added

### PR DESCRIPTION
**Pull request by knyga**
I am working on the project where node-thermal-printer is used for printing multilingual documents, mainly with support for ukrainian and russian texts.
SLOVENIA charset didn't worked for me and it would not work for quite some cases because it doesn't contain characters used in the language.
EPSON printer supports more character sets then listed. I added them in the config.
Also, I added a possibility to specify encoding which you would prefer to use with the test. Encoding logic may be considered as redundant, so code could depend on buffer, but I would suggest to have it inside the module for the simplicity of the use for the end user.

### CODE REVIEW

**Comment by Klemen1337** [comment]
@knyga can you give me your examples for ukrainian and russian texts, so I can test it?

**Comment by knyga** [comment]
I suggest to do tests on pangram (lorem ipsum like):
https://uk.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D0%B3%D1%80%D0%B0%D0%BC%D0%B0
https://ru.wikipedia.org/wiki/%D0%9F%D0%B0%D0%BD%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0

**Comment by Klemen1337** [comment]
I am interested in your encoding settings because I cant get Cyrillic to print.

**Comment by knyga** [comment]
There are few options, but I am using CP1125 for ukrainian and CP1251 for russian

**Comment by knyga** [comment]
@Klemen1337 I see you did changes based on my pull request without merging it. You are welcome

**Comment by Klemen1337** [comment]
I merged yours and an older pull request https://github.com/Klemen1337/node-thermal-printer/pull/81 that automatically selects encoding.

Thank you :beer:

**Pull request closed without merging**
